class MockChallenges:
    PREDICT_OUTCOME_MOCK_INPUT = "Bouncer Pull Perfect"
    PREDICT_OUTCOME_MOCK_INPUT_PARSED_VALUES = ["BOUNCER", "PULL", "PERFECT"]


class Result:
    PREDICT_OUTCOME_INPUT_PARSER_RESULTS = "BOUNCER PULL PERFECT"
    PREDICT_OUTCOME_RESULTS = "4 runs"
