class MockChallenges:
    PREDICT_OUTCOME_MOCK_INPUT = "Bouncer Pull Perfect"
    PREDICT_OUTCOME_MOCK_INPUT_PARSED_VALUES = ["BOUNCER", "PULL", "PERFECT"]
    PREDICT_OUTCOME_MOCK_INPUT_PARSED_VALUES_2 = ["BOUNCER", "PULL", "LATE"]


class Result:
    pass
